version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus-data:/prometheus/data
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/prometheus/alert.rules.yml:ro
    ports:
      - 9090:9090
    command:
      - "--web.enable-lifecycle"
    restart: always
    networks:
      - promnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
    networks:
      - promnet
    ports:
      - 5000:3000
    user: root

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager-data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    restart: always
    networks:
      - promnet
    user: root

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 18080:8080
    restart: always
    networks:
      - promnet
    user: root

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - "--config.file=/config/blackbox.yml"
    ports:
      - 9115:9115
    restart: always
    networks:
      - promnet
    user: root

networks:
  promnet:
    driver: bridge