#!/usr/bin/env sh

COMMIT_MESSAGE_FILE_PATH=$1  
MESSAGE=$(cat "$COMMIT_MESSAGE_FILE_PATH")

# 커밋 메시지가 있을 때만 이슈 넘버를 추가한다. 
if [[ $(head -1 "$COMMIT_MESSAGE_FILE_PATH") == '' ]]; then  
  exit 0  
fi

ISSUE_NUMBER=$(git branch | grep '\*' | sed 's/* //' | sed 's/^.*\(#[0-9]*\)/\1/')

# 커밋 메시지에 이슈 넘버가 없을 때만 이슈 넘버를 추가한다.
if [[ "$MESSAGE" =~ \["$ISSUE_NUMBER"\] ]]; then
  exit 0
fi

printf "%s\n\n[%s]" "$MESSAGE" "$ISSUE_NUMBER" > "$COMMIT_MESSAGE_FILE_PATH"
