const $scale = {
  grey00: "var(--mm-scale-color-grey-00)",
  grey50: "var(--mm-scale-color-grey-50)",
  grey100: "var(--mm-scale-color-grey-100)",
  grey200: "var(--mm-scale-color-grey-200)",
  grey300: "var(--mm-scale-color-grey-300)",
  grey400: "var(--mm-scale-color-grey-400)",
  grey500: "var(--mm-scale-color-grey-500)",
  grey600: "var(--mm-scale-color-grey-600)",
  grey700: "var(--mm-scale-color-grey-700)",
  grey800: "var(--mm-scale-color-grey-800)",
  grey900: "var(--mm-scale-color-grey-900)",
  coral50: "var(--mm-scale-color-coral-50)",
  coral100: "var(--mm-scale-color-coral-100)",
  coral200: "var(--mm-scale-color-coral-200)",
  coral300: "var(--mm-scale-color-coral-300)",
  coral400: "var(--mm-scale-color-coral-400)",
  coral500: "var(--mm-scale-color-coral-500)",
  coral600: "var(--mm-scale-color-coral-600)",
  coral700: "var(--mm-scale-color-coral-700)",
  coral800: "var(--mm-scale-color-coral-800)",
  coral900: "var(--mm-scale-color-coral-900)",
  coral950: "var(--mm-scale-color-coral-950)",
  brown50: "var(--mm-scale-color-brown-50)",
  brown100: "var(--mm-scale-color-brown-100)",
  brown200: "var(--mm-scale-color-brown-200)",
  brown300: "var(--mm-scale-color-brown-300)",
  brown400: "var(--mm-scale-color-brown-400)",
  brown500: "var(--mm-scale-color-brown-500)",
  brown600: "var(--mm-scale-color-brown-600)",
  brown700: "var(--mm-scale-color-brown-700)",
  brown800: "var(--mm-scale-color-brown-800)",
  brown900: "var(--mm-scale-color-brown-900)",
  brown950: "var(--mm-scale-color-brown-950)",
};

const $semantic = {
  textWhite: "var(--mm-semantic-color-text-white-default)",
  bgWhite: "var(--mm-semantic-color-bg-white-default)",
  textDisabled: "var(--mm-semantic-color-text-disabled)",
  bgDisabled: "var(--mm-semantic-color-bg-disabled)",
  primary: "var(--mm-semantic-color-primary)",
  primaryHover: "var(--mm-semantic-color-primary-hover)",
  primaryLow: "var(--mm-semantic-color-primary-low)",
  primaryLowHover: "var(--mm-semantic-color-primary-low-hover)",
  secondary: "var(--mm-semantic-color-secondary)",
  secondaryHover: "var(--mm-semantic-color-secondary-hover)",
  secondaryLow: "var(--mm-semantic-color-secondary-low)",
  secondaryLowHover: "var(--mm-semantic-color-secondary-low-hover)",
  border: "var(--mm-semantic-color-border)",
  success: "var(--mm-semantic-color-success)",
  danger: "var(--mm-semantic-color-danger)",
  badgeBlue: "var(--mm-semantic-color-badge-blue)",
  badgeBlueBg: "var(--mm-semantic-color-badge-blue-bg)",
  badgeGreen: "var(--mm-semantic-color-badge-green)",
  badgeGreenBg: "var(--mm-semantic-color-badge-green-bg)",
  badgeOrange: "var(--mm-semantic-color-badge-orange)",
  badgeOrangeBg: "var(--mm-semantic-color-badge-orange-bg)",
  badgePurple: "var(--mm-semantic-color-badge-purple)",
  badgePurpleBg: "var(--mm-semantic-color-badge-purple-bg)",
  badgeRed: "var(--mm-semantic-color-badge-red)",
  badgeRedBg: "var(--mm-semantic-color-badge-red-bg)",
  badgeTeal: "var(--mm-semantic-color-badge-teal)",
  badgeTealBg: "var(--mm-semantic-color-badge-teal-bg)",
  badgeYellow: "var(--mm-semantic-color-badge-yellow)",
  badgeYellowBg: "var(--mm-semantic-color-badge-yellow-bg)",
};

const color = { $scale, $semantic };
export default color;
